import { ApiProperty } from '@nestjs/swagger';
import { IsString, IsNotEmpty } from 'class-validator';

export class UpdateFcmTokenDto {
  @ApiProperty({
    description: 'FCM device token generated by Firebase on the mobile device',
    example: 'dGhpcyBpcyBhIHNhbXBsZSBmY20gdG9rZW4...',
  })
  @IsString()
  @IsNotEmpty()
  token: string;
}